generic-service:
  nameOverride: hmpps-dpr-tools-ui-probation

  replicaCount: 2

  image:
    repository: quay.io/hmpps/hmpps-dpr-tools-ui
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: dpr-tools-cert
    modsecurity_enabled: true
    modsecurity_audit_enabled: false
    modsecurity_snippet: |
      SecRuleEngine On
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET POST OPTIONS"
      SecDefaultAction "phase:2,pass,log,tag:github_team=hmpps-digital-prison-reporting"
      SecDefaultAction "phase:4,pass,log,tag:github_team=hmpps-digital-prison-reporting"
      SecRuleRemoveById 932110
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: '360'
      nginx.ingress.kubernetes.io/proxy-body-size: 100m
      nginx.ingress.kubernetes.io/server-snippet: |
        client_max_body_size 100m;

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: 'production'
    REDIS_TLS_ENABLED: 'true'
    TOKEN_VERIFICATION_ENABLED: 'true'
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/'
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    TOKEN_VERIFICATION_API_URL: https://token-verification-api-dev.prison.service.justice.gov.uk
    INGRESS_URL: dpr-tools.probation.hmpps.service.justice.gov.uk
    SYSTEM_TOKEN_ENABLED: true

  namespace_secrets:
    hmpps-dpr-tools-ui:
      APPINSIGHTS_INSTRUMENTATIONKEY: 'APPINSIGHTS_INSTRUMENTATIONKEY'
    hmpps-dpr-tools-ui-ec-cluster-output:
      REDIS_HOST: 'primary_endpoint_address'
      REDIS_AUTH_TOKEN: 'auth_token'
    ui-session-secret:
      SESSION_SECRET: 'session_secret'
    hmpps-auth:
      API_CLIENT_ID: 'api_client_id'
      API_CLIENT_SECRET: 'api_client_secret'
      SYSTEM_CLIENT_ID: 'system_client_id'
      SYSTEM_CLIENT_SECRET: 'system_client_secret'
    flipt:
      FLIPT_API_KEY: 'API_KEY'
      FLIPT_NAMESPACE: 'NAMESPACE'
      FLIPT_URL: 'URL'

  # Group name source: https://github.com/ministryofjustice/hmpps-ip-allowlists/blob/main/ip-allowlist-groups.yaml
  allowlist:
    groups:
      - circleci
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-dpr-tools-ui-probation
