# Per environment values which override defaults in hmpps-dpr-tools-ui/values.yaml

generic-service:
  ingress:
    host: dpr-tools.probation.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: 'https://dpr-tools.probation.hmpps.service.justice.gov.uk'
    HMPPS_AUTH_URL: 'https://sign-in.hmpps.service.justice.gov.uk/auth'
    HMPPS_MANAGE_USERS_URL: 'https://manage-users-api.hmpps.service.justice.gov.uk'
    TOKEN_VERIFICATION_API_URL: 'https://token-verification-api.prison.service.justice.gov.uk'
    API_URL: 'http://dpr-tools-api.probation.hmpps.service.justice.gov.uk'
    TOKEN_VERIFICATION_ENABLED: true
    AUTHORISED_ROLES: ROLE_PRISONS_REPORTING_TOOLS_USER
    DPS_URL: 'https://dps.prison.service.justice.gov.uk'
    REQUIRED_AUTH_SOURCES: 'delius'

  scheduledDowntime:
    enabled: true
    startup: '40 7 * * 1-5' # Start at 7.40am UTC Monday-Friday
    shutdown: '20 20 * * 1-5' # Stop at 8.20pm UTC Monday-Friday

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: probation-frontend-alerts-prod
