name: Pipeline

on:
  push:
    branches: ['**']
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  pipeline:
    uses: ministryofjustice/hmpps-reporting-workflows/.github/workflows/frontend_node_pipeline.yml@v1
    secrets: inherit
    with:
      enable-probation: true
      probation-chart-name: hmpps-dpr-tools-ui-probation
      probation-release-name: hmpps-dpr-tools-ui-probation
      deploy-dev-on-feature-branches: true
      deploy-ref: 'refs/heads/PDHD-305'
      node-version: '24'
      slack-channel: 'dpr_cicd_alerts'
      # Image: ghcr.io/ministryofjustice/hmpps-dpr-tools-ui
