name: PR preparation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  preparation:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 24

      - run: npm ci --no-audit

      - name: Add linting fixes
        run: npm run lint:fix

      - name: Commit linting fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Linting fixes

      - name: Calculate test coverage
        run: |
          npm run test > logs.txt
          grep '% Stmts' logs.txt -A2 > message.txt

      - name: PR comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: coverage
          filePath: message.txt
